### ISSUE TITLE
httpx.ReadTimeout: The read operation timed out

### ISSUE THREAD

**Issue by Sieboldianus** [yaph/wikidata-dl#5]
* wikidata-dl version: Release 2022.11.24
* Python version: Python 3.9.2
* Operating System: Debian 11

### Description

I am trying to replicate a SPARQL query [that works online on query.wikidata.org/](https://w.wiki/77UJ) with `wikidata-dl`, but I get timeout exceptions.

(the query is supposed to return all Wikidata entries that relate to Events in a particular location/region. I get 223 results in 53740 ms on query.wikidata.org.

<details><summary>SPARQL query</summary>

```
#title: All events in Nevada
SELECT ?event ?eventLabel ?date ?location
WITH {
  SELECT DISTINCT ?event ?date ?location
  WHERE {
    # find events
    wd:Q1227 wdt:P625 ?nevada. 
    ?event wdt:P31/wdt:P279* wd:Q1190554.
           # wdt:P17 wd:Q30;
    # with a point in time or start date
    OPTIONAL { ?event wdt:P585 ?date. }
    OPTIONAL { ?event wdt:P580 ?date. }
    ?event wdt:P625 ?location.
    FILTER(geof:distance(?location, ?nevada) < 400).
  }
  LIMIT 1000
} AS %i
WHERE {
  INCLUDE %i
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en" . }
}
```

</details>

### What I Did

```
sudo apt install libcurl4-openssl-dev libssl-dev
python3 -m venv venv
source ./venv/bin/activate
pip install wikidata-dl
wikidata-dl ./nevada-events.sparql
```

<details><summary>Traceback</summary>

```

(venv) 08:39:55 alex@TUD ../EventQuery wikidata-dl ./nevada-events.sparql
Traceback (most recent call last):
  File "../EventQuery/venv/lib/python3.9/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "../EventQuery/venv/lib/python3.9/site-packages/httpcore/_backends/sync.py", line 28, in read
    return self._sock.recv(max_bytes)
  File "/usr/lib/python3.9/ssl.py", line 1226, in recv
    return self.read(buflen)
  File "/usr/lib/python3.9/ssl.py", line 1101, in read
    return self._sslobj.read(len)
socket.timeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../EventQuery/venv/lib/python3.9/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "../EventQuery/venv/lib/python3.9/site-packages/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "../EventQuery/venv/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 262, in handle_request
    raise exc
  File "../EventQuery/venv/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 245, in handle_request
    response = connection.handle_request(request)
  File "../EventQuery/venv/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 96, in handle_request
    return self._connection.handle_request(request)
  File "../EventQuery/venv/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 121, in handle_request
    raise exc
  File "../EventQuery/venv/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 99, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "../EventQuery/venv/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 164, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "../EventQuery/venv/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 200, in _receive_event
    data = self._network_stream.read(
  File "../EventQuery/venv/lib/python3.9/site-packages/httpcore/_backends/sync.py", line 28, in read
    return self._sock.recv(max_bytes)
  File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "../EventQuery/venv/lib/python3.9/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../EventQuery/venv/bin/wikidata-dl", line 8, in <module>
    sys.exit(main())
  File "../EventQuery/venv/lib/python3.9/site-packages/wikidata_dl/cli.py", line 33, in main
    result = wikidata.get(argv.query_file.read_text(), argv.format)
  File "../EventQuery/venv/lib/python3.9/site-packages/wikidata_dl/wikidata.py", line 92, in get
    resp = httpx.get(api_endpoint, params=params, headers=headers)
  File "../EventQuery/venv/lib/python3.9/site-packages/httpx/_api.py", line 189, in get
    return request(
  File "../EventQuery/venv/lib/python3.9/site-packages/httpx/_api.py", line 100, in request
    return client.request(
  File "../EventQuery/venv/lib/python3.9/site-packages/httpx/_client.py", line 814, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "../EventQuery/venv/lib/python3.9/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
  File "../EventQuery/venv/lib/python3.9/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
  File "../EventQuery/venv/lib/python3.9/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
  File "../EventQuery/venv/lib/python3.9/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
  File "../EventQuery/venv/lib/python3.9/site-packages/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "../EventQuery/venv/lib/python3.9/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: The read operation timed out
```

</details>

**Comment by yaph** [comment]
I fixed this in the latest release. You can now use `--timeout 0` to turn off timeouts or set them to a high value. I could download the result from your query.

**Comment by Sieboldianus** [comment]
Thank you for your response and fix!
